### ISSUE TITLE
Unable to get issue comment with id: [...]

### ISSUE THREAD

**Issue by DecimalTurn** [IEvangelist/profanity-filter#41]
I'm getting an error when the action tries to edit access a comment:
https://github.com/DecimalTurn/VBA-on-GitHub-Automations/actions/runs/10566141857

(This prevents the action from applying the filter on [this comment](https://github.com/DecimalTurn/VBA-on-GitHub-Automations/issues/79#issuecomment-2310943199)).

<details>
<summary>My yaml file</summary>

```yaml
name: Comments filter

on:
  issue_comment:
    types: [created, edited]
#  issues:
#    types: [opened, edited, reopened]
#  pull_request:
#    types: [opened, edited, reopened]

permissions:
  issues: write
  pull-requests: write

jobs:
  apply-filter:
    name: Apply comment filter
    runs-on: ubuntu-latest

    steps:
    
    # DDOS protection (optional - mostly useful for self-hosted GitHub servers)
    #- name: Harden Runner
    #  uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
    #  with:
    #    egress-policy: audit

    - name: Comment filter
      if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]'  }}
      uses: IEvangelist/profanity-filter@7b35b30e0d01d3c4a63a57b2ec5db0768bc4d53b # v1.0.74
      id: profanity-filter
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        replacement-strategy: redacted-rectangle
```

</details>
